
-- DAHA ÖNCE EKLEDİĞİNİZ TABLOLARI SİLER
DROP SCHEMA PUBLIC CASCADE;
CREATE SCHEMA PUBLIC;


-- TABLOLARI EKLER
-- KLİNİKLER TABLOSU
CREATE TABLE KLINIKLER(
	KLINIK_NO INT PRIMARY KEY,		-- KLİNİĞİN NUMARASI
	KLINIK_AD VARCHAR(20)			-- KLİNİĞİN ADI
);

-- DOKTORLAR TABLOSU
CREATE TABLE DOKTORLAR(
	DOKTOR_NO BIGINT PRIMARY KEY,			-- DOKTORUN KIMLIK NUMARASI
	DOKTOR_AD VARCHAR(20),					-- ADI
	DOKTOR_SOYAD VARCHAR(20),				-- SOYADI
	DOKTOR_KLINIK_NO INT,					-- ÇALIŞTIĞI KLİNİĞİN NUMARASI
	DOKTOR_KULLANICI_AD VARCHAR(20),		-- GİRIŞ İÇİN DOKTORUN KULLANICI ADI
	DOKTOR_SIFRE VARCHAR(20),				-- GİRİŞ İÇİN DOKTORUN ŞİFRESİ
	FOREIGN KEY(DOKTOR_KLINIK_NO) REFERENCES KLINIKLER(KLINIK_NO) ON DELETE CASCADE ON UPDATE CASCADE
);

-- KAYITLI HASTALAR TABLOSU
CREATE TABLE KAYITLI_HASTALAR(
	HASTA_NO BIGINT PRIMARY KEY,			-- HASTANIN KİMLİĞİ
	HASTA_AD VARCHAR(20),				-- HASTANIN ADI
	HASTA_SOYAD VARCHAR(20),			-- HASTANIN SOYADI
	HASTA_SIGORTA_DURUMU INT			-- HASTA SİGORTALI İSE 1 DEĞİLSE 0
);

-- RANDEVULAR TABLOSU
CREATE TABLE RANDEVULAR(
	RANDEVU_NO BIGINT PRIMARY KEY,			-- RANDEVU NUMARASI
	HASTA_NO BIGINT,						-- HASTANIN KİMLİĞİ
	DOKTOR_NO BIGINT,						-- DOKTORUN KİMLİĞİ
	KLINIK_NO INT,							-- RADENVU HANGİ KLİNİKTEN ALINDI
	RANDEVU_TARIHI TIMESTAMP,				-- RANDEVU TARİHİ
	RANDEVU_DURUMU INT,						-- HASTA KAYITLILAR TABLOSUNDA İSE RANDEVU ALMA ESNASINDE DİREK 1 OLARAK İŞLENMELİ YOKSA 0
	FOREIGN KEY(DOKTOR_NO) REFERENCES DOKTORLAR(DOKTOR_NO) ON DELETE CASCADE ON UPDATE CASCADE
);

-- MUAYENELER TABLOSU
CREATE TABLE MUAYENELER(
	MUAYENE_NO BIGSERIAL PRIMARY KEY,
	HASTA_NO BIGINT,						-- HASTANIN KİMLİĞİ
	DOKTOR_NO BIGINT,						-- DOKTORUN KİMLİĞİ
	MUAYENE_UCRETI INT,						-- MUAYENE UCRETI SIGORTASI VARSA INDİRİM YAPILMASI LAZIM
	MUAYENE_ACIKLAMASI VARCHAR,				-- DOKTORUN YAZACAĞI AÇIKLAMA
	VERILEN_DOKUMAN VARCHAR,				-- RAPOR, REÇETE VEYA SEVK KAĞIDI
	ODEME_DURUMU INT,						-- ÜCRET ÖDENDİ Mİ 1 YOKSA 0
	FOREIGN KEY(HASTA_NO) REFERENCES KAYITLI_HASTALAR(HASTA_NO) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(DOKTOR_NO) REFERENCES DOKTORLAR(DOKTOR_NO) ON DELETE CASCADE ON UPDATE CASCADE
	
);


-- ÇALIŞANLARIN TABLOSU GİRİŞ İÇİN
CREATE TABLE CALISANLAR(
	CALISAN_KULLANICI_AD VARCHAR(20) PRIMARY KEY,		-- ÇALIŞANLARIN KULLANICI ADI
	CALISAN_SIFRE VARCHAR(20),							-- ÇALIŞANIN ŞİFRESİ
	CALISAN_TIPI VARCHAR(20)							-- ÇALIŞAN TÜRÜ GOREVLI, KAYIT GOREVLİSİ, VEZNE
);

-- KISITLARIN AYRICA KODLARI
ALTER TABLE DOKTORLAR ADD FOREIGN KEY(DOKTOR_KLINIK_NO) REFERENCES KLINIKLER(KLINIK_NO) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RANDEVULAR ADD FOREIGN KEY(DOKTOR_NO) REFERENCES DOKTORLAR(DOKTOR_NO) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE MUAYENELER ADD FOREIGN KEY(HASTA_NO) REFERENCES KAYITLI_HASTALAR(HASTA_NO) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE MUAYENELER ADD FOREIGN KEY(DOKTOR_NO) REFERENCES DOKTORLAR(DOKTOR_NO) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE SEQUENCE RANDEVU_NO_GENERATOR
START WITH 1
INCREMENT BY 1
MAXVALUE 1000
NO CYCLE;
