/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sifapoliklinigi;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author sayid
 */
public class DoktorEklemeSayfasi extends javax.swing.JPanel {

    /**
     * Creates new form doktorEklemeSayfasi
     */
    
    private Doktor doktor;
    private Gorevli gorevli;
    private Klinik klinik;
    private Hasta hasta;
    private Randevu randevu;
    private Muayene muayene;
    PostgreConnector postgresql = new PostgreConnector();
    
    public DoktorEklemeSayfasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doktorEkleAdTextField = new javax.swing.JTextField();
        doktorEkleSoyadTextField = new javax.swing.JTextField();
        doktorEkleKimlikNoTextField = new javax.swing.JTextField();
        doktorEkleKliniklarComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        doktorEkleKullaniciAdTextField = new javax.swing.JTextField();
        doktorEkleSifreTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        doktorEkleButon = new javax.swing.JButton();

        doktorEkleAdTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        doktorEkleSoyadTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        doktorEkleKimlikNoTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        doktorEkleKliniklarComboBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        doktorEkleKliniklarComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz" }));
        doktorEkleKliniklarComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktorEkleKliniklarComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Kimlik Numarası");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Ad");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Soyad");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Çalışacağı Klinik");

        doktorEkleKullaniciAdTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        doktorEkleSifreTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Kullanıcı Ad");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Şifre");

        doktorEkleButon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        doktorEkleButon.setText("Doktor Ekle");
        doktorEkleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktorEkleButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(doktorEkleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doktorEkleKullaniciAdTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doktorEkleKimlikNoTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doktorEkleAdTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doktorEkleSoyadTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doktorEkleKliniklarComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doktorEkleSifreTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doktorEkleKimlikNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doktorEkleAdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doktorEkleSoyadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doktorEkleKliniklarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doktorEkleKullaniciAdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doktorEkleSifreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(doktorEkleButon)
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doktorEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktorEkleButonActionPerformed
        // TODO add your handling code here:
        if (checkComponents()) {
            long kimlikNo = Long.parseLong(doktorEkleKimlikNoTextField.getText());
            String ad = doktorEkleAdTextField.getText();
            String soyad = doktorEkleSoyadTextField.getText();
            String klinikNo = doktorEkleKliniklarComboBox.getSelectedItem().toString().split(" ")[0];
            String kullanicAd = doktorEkleKullaniciAdTextField.getText();
            String sifre = doktorEkleSifreTextField.getText();

            if (new Doktor(kimlikNo, ad, soyad, Integer.parseInt(klinikNo), kullanicAd, sifre).veriTabaninaIsle()) {
                JOptionPane.showMessageDialog(this, "Eklendi");
                doktorEkleKimlikNoTextField.setText("");
                doktorEkleAdTextField.setText("");
                doktorEkleSoyadTextField.setText("");
                doktorEkleKliniklarComboBox.setSelectedIndex(0);
                doktorEkleKullaniciAdTextField.setText("");
                doktorEkleSifreTextField.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Hata Oluştu, Lütfen Bilgileri Kontrol Ediniz");
            }
        }else{
            System.out.println("bos alan");
            JOptionPane.showMessageDialog(this, "Hata Oluştu, Boş Alanları Doldurunuz");
        }

    }//GEN-LAST:event_doktorEkleButonActionPerformed

    private void doktorEkleKliniklarComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktorEkleKliniklarComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doktorEkleKliniklarComboBoxActionPerformed

    public void updateDoktorEkleKlinikComboBox(){ 
        doktorEkleKliniklarComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz" }));
        Connection con = postgresql.getInstance(); 
        
        try{       
            Statement stmt=con.createStatement(); 
            String Komut;
            Komut = String.format("Select *from klinikler");
            ResultSet rs = stmt.executeQuery(Komut);
            
            while (rs.next()) {
                doktorEkleKliniklarComboBox.addItem(rs.getString("KLINIK_NO")+' '+rs.getString("KLINIK_AD"));
            }
        }catch(SQLException e){ 
            System.out.println(e);
            System.out.println("SQL EXception");
        }
    }
    
    public boolean checkComponents(){
        return !doktorEkleKimlikNoTextField.getText().equals("") && !doktorEkleAdTextField.getText().equals("") &&
                !doktorEkleSoyadTextField.getText().equals("") && doktorEkleKliniklarComboBox.getSelectedIndex() != 0 &&
                !doktorEkleKullaniciAdTextField.getText().equals("") && !doktorEkleSifreTextField.getText().equals("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField doktorEkleAdTextField;
    private javax.swing.JButton doktorEkleButon;
    private javax.swing.JTextField doktorEkleKimlikNoTextField;
    private javax.swing.JComboBox<String> doktorEkleKliniklarComboBox;
    private javax.swing.JTextField doktorEkleKullaniciAdTextField;
    private javax.swing.JTextField doktorEkleSifreTextField;
    private javax.swing.JTextField doktorEkleSoyadTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
