/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sifapoliklinigi;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;

import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author sayid
 */
public class GirisEkrani extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private Doktor doktor;
    private Gorevli gorevli;
    PostgreConnector postgresql = new PostgreConnector();
    
    DoktorAnaSayfasi doktorAnaSayfasi;
    DoktorEklemeSayfasi doktorEklemeSayfasi;
    GorevliAnaSayfasi gorevliAnaSayfasi;
    HastaBilgisiSayfasi hastaBilgisiSayfasi;
    HastaKayitSayfasi hastaKayitSayfasi;
    HastaOdemeSayfasi hastaOdemeSayfasi;
    HastaRandevuSayfasi hastaRandevuSayfasi;
    KayitGorevlisiAnaSayfasi kayitGorevlisiAnaSayfasi;
    KlinikEklemeSayfasi klinikEklemeSayfasi;
    VezneAnaSayfasi vezneAnaSayfasi;
    
    
    
    public GirisEkrani() {
        initComponents();
        girisUyariMesaji.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        girisEkranSidePanel = new javax.swing.JPanel();
        gorevliIcon1 = new javax.swing.JLabel();
        gorevliSidePanel = new javax.swing.JPanel();
        hastaRandevuIslemleri = new javax.swing.JLabel();
        klinikIslemleri = new javax.swing.JLabel();
        doktorIslemleri = new javax.swing.JLabel();
        gorevliIcon = new javax.swing.JLabel();
        gorevliAnaSayfasiLabel = new javax.swing.JLabel();
        gorevliCikis = new javax.swing.JLabel();
        kayitGorevlisiSidePanel = new javax.swing.JPanel();
        kayitGorevlisiIcon = new javax.swing.JLabel();
        hastaKayitIslemleri = new javax.swing.JLabel();
        kayitGorevlisiAnaSayfasiLabel = new javax.swing.JLabel();
        kayitGorevlisiCikis = new javax.swing.JLabel();
        doktorSidePanel = new javax.swing.JPanel();
        hastaBilsgiIslemleriLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        doktorAnaSayfasiLabel = new javax.swing.JLabel();
        doktorCikis = new javax.swing.JLabel();
        vezneSidePanel = new javax.swing.JPanel();
        vezneIcon = new javax.swing.JLabel();
        vezneAnaSayfasiLabel = new javax.swing.JLabel();
        vezneCikis = new javax.swing.JLabel();
        hastaOdemeIslemleri = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        girisEkranPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        kullaniciTipComboBox = new javax.swing.JComboBox<>();
        girisButton = new javax.swing.JButton();
        girisUyariMesaji = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidePanel.setBackground(new java.awt.Color(102, 153, 255));
        sidePanel.setLayout(new java.awt.CardLayout());

        girisEkranSidePanel.setBackground(new java.awt.Color(51, 153, 255));

        gorevliIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sifapoliklinigi/hospital(2).png"))); // NOI18N

        javax.swing.GroupLayout girisEkranSidePanelLayout = new javax.swing.GroupLayout(girisEkranSidePanel);
        girisEkranSidePanel.setLayout(girisEkranSidePanelLayout);
        girisEkranSidePanelLayout.setHorizontalGroup(
            girisEkranSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(girisEkranSidePanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(gorevliIcon1)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        girisEkranSidePanelLayout.setVerticalGroup(
            girisEkranSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(girisEkranSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gorevliIcon1)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        sidePanel.add(girisEkranSidePanel, "card2");

        gorevliSidePanel.setBackground(new java.awt.Color(51, 153, 255));

        hastaRandevuIslemleri.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        hastaRandevuIslemleri.setForeground(new java.awt.Color(255, 255, 255));
        hastaRandevuIslemleri.setText("Hasta Randevu İşlemleri");
        hastaRandevuIslemleri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hastaRandevuIslemleriMouseClicked(evt);
            }
        });

        klinikIslemleri.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        klinikIslemleri.setForeground(new java.awt.Color(255, 255, 255));
        klinikIslemleri.setText("Klinik İşlemleri");
        klinikIslemleri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                klinikIslemleriMouseClicked(evt);
            }
        });

        doktorIslemleri.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        doktorIslemleri.setForeground(new java.awt.Color(255, 255, 255));
        doktorIslemleri.setText("Doktor İşlemleri");
        doktorIslemleri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doktorIslemleriMouseClicked(evt);
            }
        });

        gorevliIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sifapoliklinigi/hospital(2).png"))); // NOI18N

        gorevliAnaSayfasiLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gorevliAnaSayfasiLabel.setForeground(new java.awt.Color(255, 255, 255));
        gorevliAnaSayfasiLabel.setText("Ana Sayfası");
        gorevliAnaSayfasiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gorevliAnaSayfasiLabelMouseClicked(evt);
            }
        });

        gorevliCikis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gorevliCikis.setForeground(new java.awt.Color(255, 255, 255));
        gorevliCikis.setText("Çıkış Yap");
        gorevliCikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gorevliCikisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gorevliSidePanelLayout = new javax.swing.GroupLayout(gorevliSidePanel);
        gorevliSidePanel.setLayout(gorevliSidePanelLayout);
        gorevliSidePanelLayout.setHorizontalGroup(
            gorevliSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gorevliSidePanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(gorevliSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gorevliIcon)
                    .addComponent(klinikIslemleri)
                    .addComponent(hastaRandevuIslemleri)
                    .addComponent(gorevliAnaSayfasiLabel)
                    .addComponent(doktorIslemleri)
                    .addComponent(gorevliCikis))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        gorevliSidePanelLayout.setVerticalGroup(
            gorevliSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gorevliSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gorevliIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(gorevliAnaSayfasiLabel)
                .addGap(18, 18, 18)
                .addComponent(hastaRandevuIslemleri)
                .addGap(18, 18, 18)
                .addComponent(klinikIslemleri)
                .addGap(18, 18, 18)
                .addComponent(doktorIslemleri)
                .addGap(18, 18, 18)
                .addComponent(gorevliCikis)
                .addGap(207, 207, 207))
        );

        sidePanel.add(gorevliSidePanel, "card3");

        kayitGorevlisiSidePanel.setBackground(new java.awt.Color(51, 153, 255));

        kayitGorevlisiIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sifapoliklinigi/hospital(2).png"))); // NOI18N

        hastaKayitIslemleri.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        hastaKayitIslemleri.setForeground(new java.awt.Color(255, 255, 255));
        hastaKayitIslemleri.setText("Hasta Kayıt İşlemleri");
        hastaKayitIslemleri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hastaKayitIslemleriMouseClicked(evt);
            }
        });

        kayitGorevlisiAnaSayfasiLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        kayitGorevlisiAnaSayfasiLabel.setForeground(new java.awt.Color(255, 255, 255));
        kayitGorevlisiAnaSayfasiLabel.setText("Ana Sayfası");
        kayitGorevlisiAnaSayfasiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kayitGorevlisiAnaSayfasiLabelMouseClicked(evt);
            }
        });

        kayitGorevlisiCikis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        kayitGorevlisiCikis.setForeground(new java.awt.Color(255, 255, 255));
        kayitGorevlisiCikis.setText("Çıkış Yap");
        kayitGorevlisiCikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kayitGorevlisiCikisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kayitGorevlisiSidePanelLayout = new javax.swing.GroupLayout(kayitGorevlisiSidePanel);
        kayitGorevlisiSidePanel.setLayout(kayitGorevlisiSidePanelLayout);
        kayitGorevlisiSidePanelLayout.setHorizontalGroup(
            kayitGorevlisiSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kayitGorevlisiSidePanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(kayitGorevlisiSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kayitGorevlisiCikis)
                    .addComponent(hastaKayitIslemleri, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kayitGorevlisiIcon)
                    .addComponent(kayitGorevlisiAnaSayfasiLabel))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        kayitGorevlisiSidePanelLayout.setVerticalGroup(
            kayitGorevlisiSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kayitGorevlisiSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kayitGorevlisiIcon)
                .addGap(31, 31, 31)
                .addComponent(kayitGorevlisiAnaSayfasiLabel)
                .addGap(18, 18, 18)
                .addComponent(hastaKayitIslemleri)
                .addGap(18, 18, 18)
                .addComponent(kayitGorevlisiCikis)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        sidePanel.add(kayitGorevlisiSidePanel, "card4");

        doktorSidePanel.setBackground(new java.awt.Color(51, 153, 255));

        hastaBilsgiIslemleriLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        hastaBilsgiIslemleriLabel.setForeground(new java.awt.Color(255, 255, 255));
        hastaBilsgiIslemleriLabel.setText("Hasta Bilgisi İşlemleri");
        hastaBilsgiIslemleriLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hastaBilsgiIslemleriLabelMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sifapoliklinigi/hospital(2).png"))); // NOI18N

        doktorAnaSayfasiLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        doktorAnaSayfasiLabel.setForeground(new java.awt.Color(255, 255, 255));
        doktorAnaSayfasiLabel.setText("Ana Sayfası");
        doktorAnaSayfasiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doktorAnaSayfasiLabelMouseClicked(evt);
            }
        });

        doktorCikis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        doktorCikis.setForeground(new java.awt.Color(255, 255, 255));
        doktorCikis.setText("Çıkış Yap");
        doktorCikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doktorCikisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout doktorSidePanelLayout = new javax.swing.GroupLayout(doktorSidePanel);
        doktorSidePanel.setLayout(doktorSidePanelLayout);
        doktorSidePanelLayout.setHorizontalGroup(
            doktorSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doktorSidePanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(doktorSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doktorCikis)
                    .addComponent(doktorAnaSayfasiLabel)
                    .addComponent(jLabel11)
                    .addComponent(hastaBilsgiIslemleriLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        doktorSidePanelLayout.setVerticalGroup(
            doktorSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doktorSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(31, 31, 31)
                .addComponent(doktorAnaSayfasiLabel)
                .addGap(18, 18, 18)
                .addComponent(hastaBilsgiIslemleriLabel)
                .addGap(18, 18, 18)
                .addComponent(doktorCikis)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        sidePanel.add(doktorSidePanel, "card5");

        vezneSidePanel.setBackground(new java.awt.Color(51, 153, 255));

        vezneIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sifapoliklinigi/hospital(2).png"))); // NOI18N

        vezneAnaSayfasiLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vezneAnaSayfasiLabel.setForeground(new java.awt.Color(255, 255, 255));
        vezneAnaSayfasiLabel.setText("Ana Sayfası");
        vezneAnaSayfasiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vezneAnaSayfasiLabelMouseClicked(evt);
            }
        });

        vezneCikis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vezneCikis.setForeground(new java.awt.Color(255, 255, 255));
        vezneCikis.setText("Çıkış Yap");
        vezneCikis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vezneCikisFocusGained(evt);
            }
        });
        vezneCikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vezneCikisMouseClicked(evt);
            }
        });

        hastaOdemeIslemleri.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        hastaOdemeIslemleri.setForeground(new java.awt.Color(255, 255, 255));
        hastaOdemeIslemleri.setText("Hasta Ödeme İşlemleri");
        hastaOdemeIslemleri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hastaOdemeIslemleriMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout vezneSidePanelLayout = new javax.swing.GroupLayout(vezneSidePanel);
        vezneSidePanel.setLayout(vezneSidePanelLayout);
        vezneSidePanelLayout.setHorizontalGroup(
            vezneSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vezneSidePanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(vezneSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vezneCikis)
                    .addComponent(vezneAnaSayfasiLabel)
                    .addComponent(vezneIcon)
                    .addComponent(hastaOdemeIslemleri))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        vezneSidePanelLayout.setVerticalGroup(
            vezneSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vezneSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vezneIcon)
                .addGap(43, 43, 43)
                .addComponent(vezneAnaSayfasiLabel)
                .addGap(18, 18, 18)
                .addComponent(hastaOdemeIslemleri)
                .addGap(21, 21, 21)
                .addComponent(vezneCikis)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        sidePanel.add(vezneSidePanel, "card6");

        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Kullanıcı Türü");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Kullanıcı Adı");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Şifre");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Kullanıcı Girişi");

        kullaniciTipComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "Doktor", "Görevli", "Kayıt Görevlisi", "Vezne" }));
        kullaniciTipComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciTipComboBoxActionPerformed(evt);
            }
        });

        girisButton.setText("Giriş Yap");
        girisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisButtonActionPerformed(evt);
            }
        });

        girisUyariMesaji.setForeground(new java.awt.Color(255, 0, 51));
        girisUyariMesaji.setText("Yanlış Kullanıcı Ad veya Şifre");

        javax.swing.GroupLayout girisEkranPanelLayout = new javax.swing.GroupLayout(girisEkranPanel);
        girisEkranPanel.setLayout(girisEkranPanelLayout);
        girisEkranPanelLayout.setHorizontalGroup(
            girisEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(girisEkranPanelLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addGroup(girisEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(girisEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kullaniciTipComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(girisUyariMesaji, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(girisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        girisEkranPanelLayout.setVerticalGroup(
            girisEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(girisEkranPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(kullaniciTipComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(girisButton)
                .addGap(18, 18, 18)
                .addComponent(girisUyariMesaji)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        mainPanel.add(girisEkranPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Fixed
    private void girisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisButtonActionPerformed
        // TODO add your handling code here:
        Connection conn = postgresql.getInstance();
        
        String username = userNameTextField.getText();
        String password = passwordTextField.getText();
        
        String kullaniciTipi = kullaniciTipComboBox.getSelectedItem().toString();
        
        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        formatter.format(date);
        
        if(kullaniciTipi.equalsIgnoreCase("Doktor")){
            try{
                Statement stmt = conn.createStatement();
                String query = String.format("select *from doktorlar where doktor_kullanici_ad = '%s' and doktor_sifre = '%s'", username,password);
                ResultSet rs = stmt.executeQuery(query);
                
                if(rs.next()){
                    long kimlikNo = rs.getLong("DOKTOR_NO");
                    String ad = rs.getString("DOKTOR_AD");
                    String soyad = rs.getString("DOKTOR_SOYAD");
                    int klinikNo = rs.getInt("DOKTOR_KLINIK_NO");
                    String kullaniciAd = rs.getString("DOKTOR_KULLANICI_AD");
                    String sifre = rs.getString("DOKTOR_SIFRE");
                    
                    
                    this.doktor = new Doktor(kimlikNo, ad, soyad, klinikNo, kullaniciAd, sifre);
                    System.out.println(doktor);
                    
                    doktorAnaSayfasi = new DoktorAnaSayfasi(this.doktor);
                    mainPanel.add(doktorAnaSayfasi);
                    doktorAnaSayfasi.setDoktorTarihLabel(java.time.LocalDate.now().toString());
                    doktorAnaSayfasi.setDoktorAdSoyadProfil(ad+' '+soyad);
                    
                    girisEkranPanel.setVisible(false);
                    girisEkranSidePanel.setVisible(false);
                    //doktorAnaSayfasi.setVisible(true);
                    doktorAnaSayfasi.setVisible(true);
                    doktorSidePanel.setVisible(true);
                }else{
                    System.out.println("Sifre veya kullanici ad yanlis");
                    girisUyariMesaji.setVisible(true);
                }
            
            
            }catch(SQLException e){
                System.out.println(e);
                System.out.println("SQL EXception");
            }
            
        }else if(kullaniciTipi.equalsIgnoreCase("Görevli")){
            try{
                Statement stmt = conn.createStatement();
                String query = String.format("select *from Calisanlar where calisan_kullanici_ad = '%s' and calisan_sifre = '%s' and calisan_tipi = 'Sistem'", username,password);
                ResultSet rs = stmt.executeQuery(query);
                
                if(rs.next()){
                    String kullaniciAd = rs.getString("CALISAN_KULLANICI_AD");
                    String sifre = rs.getString("CALISAN_SIFRE");
                    String tip = rs.getString("CALISAN_TIPI");
                    
                    this.gorevli = new Gorevli(kullaniciAd, sifre, tip);
                    System.out.println(gorevli);
                    
                    gorevliAnaSayfasi = new GorevliAnaSayfasi(gorevli);
                    mainPanel.add(gorevliAnaSayfasi);
                    gorevliAnaSayfasi.setGorevliAdSoyadProfile(kullaniciAd);
                    gorevliAnaSayfasi.setGorevliTarihLabel(java.time.LocalDate.now().toString());
                    
                    girisEkranPanel.setVisible(false);
                    girisEkranSidePanel.setVisible(false);
                    //gorevliAnaSayfasi.setVisible(true);
                    gorevliAnaSayfasi.setVisible(true);
                    gorevliSidePanel.setVisible(true);
                }else{
                    System.out.println("Sifre veya kullanici ad yanlis");
                    girisUyariMesaji.setVisible(true);
                }
            
            
            }catch(SQLException e){
                System.out.println(e);
                System.out.println("SQL EXception");
            }
            
        }else if(kullaniciTipi.equalsIgnoreCase("Kayıt Görevlisi")){
            try{
                Statement stmt = conn.createStatement();
                String query = String.format("select *from Calisanlar where calisan_kullanici_ad = '%s' and calisan_sifre = '%s' and calisan_tipi = 'Kayit'", username,password);
                ResultSet rs = stmt.executeQuery(query);
                
                if(rs.next()){
                    String kullaniciAd = rs.getString("CALISAN_KULLANICI_AD");
                    String sifre = rs.getString("CALISAN_SIFRE");
                    String tip = rs.getString("CALISAN_TIPI");
                    
                    this.gorevli = new Gorevli(kullaniciAd, sifre, tip);
                    System.out.println(gorevli);
                    
                    kayitGorevlisiAnaSayfasi = new KayitGorevlisiAnaSayfasi(gorevli);
                    mainPanel.add(kayitGorevlisiAnaSayfasi);
                    kayitGorevlisiAnaSayfasi.setKayitGorevlisiAdSoyadProfil(kullaniciAd);
                    kayitGorevlisiAnaSayfasi.setKayitGorevlisiTarihLabel(java.time.LocalDate.now().toString());
                    
                    girisEkranPanel.setVisible(false);
                    girisEkranSidePanel.setVisible(false);
                    //kayitGorevlisiAnaSayfasi.setVisible(true);
                    kayitGorevlisiAnaSayfasi.setVisible(true);
                    kayitGorevlisiSidePanel.setVisible(true);
                }else{
                    System.out.println("Sifre veya kullanici ad yanlis");
                    girisUyariMesaji.setVisible(true);
                }
            
            
            }catch(SQLException e){
                System.out.println(e);
                System.out.println("SQL EXception");
            }
        }else if(kullaniciTipi.equalsIgnoreCase("Vezne")){
            try{
                Statement stmt = conn.createStatement();
                String query = String.format("select *from Calisanlar where calisan_kullanici_ad = '%s' and calisan_sifre = '%s' and calisan_tipi = 'Vezne'", username,password);
                ResultSet rs = stmt.executeQuery(query);
                
                if(rs.next()){
                    String kullaniciAd = rs.getString("CALISAN_KULLANICI_AD");
                    String sifre = rs.getString("CALISAN_SIFRE");
                    String tip = rs.getString("CALISAN_TIPI");
                    
                    this.gorevli = new Gorevli(kullaniciAd, sifre, tip);
                    System.out.println(gorevli);
                    
                    vezneAnaSayfasi = new VezneAnaSayfasi(gorevli);
                    mainPanel.add(vezneAnaSayfasi);
                    vezneAnaSayfasi.setVezneAdSoyadProfil(kullaniciAd);
                    vezneAnaSayfasi.setVezneTarihLabel(java.time.LocalDate.now().toString());
                    
                    girisEkranPanel.setVisible(false);
                    girisEkranSidePanel.setVisible(false);
                    //vezneAnaSayfasi.setVisible(true);
                    vezneAnaSayfasi.setVisible(true);
                    vezneSidePanel.setVisible(true);
                }else{
                    System.out.println("Sifre veya kullanici ad yanlis");
                    girisUyariMesaji.setVisible(true);
                }
            
            
            }catch(SQLException e){
                System.out.println(e);
                System.out.println("SQL EXception");
            }
        }else{
            JOptionPane.showMessageDialog(this,"Lütfen Kullanıcı Türü Seçimi Yapınız");
        } 
   
    }//GEN-LAST:event_girisButtonActionPerformed

    
    private void gorevliCikisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gorevliCikisMouseClicked
        // TODO add your handling code here:
        gorevliAnaSayfasi.setVisible(false);
        gorevliSidePanel.setVisible(false);
        
        if(doktorEklemeSayfasi != null){
            doktorEklemeSayfasi.setVisible(false);
        }
                
        
        if(hastaRandevuSayfasi != null){
            hastaRandevuSayfasi.setVisible(false);
        }
        
        if(klinikEklemeSayfasi != null){
            klinikEklemeSayfasi.setVisible(false);
        }
        
        girisEkranPanel.setVisible(true);
        girisEkranSidePanel.setVisible(true);
        
    }//GEN-LAST:event_gorevliCikisMouseClicked

    private void kayitGorevlisiCikisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayitGorevlisiCikisMouseClicked
        // TODO add your handling code here:
        kayitGorevlisiSidePanel.setVisible(false);
        kayitGorevlisiAnaSayfasi.setVisible(false);
        
        if(hastaKayitSayfasi != null){
            hastaKayitSayfasi.setVisible(false);
        }
        
        girisEkranPanel.setVisible(true);
        girisEkranSidePanel.setVisible(true);
    }//GEN-LAST:event_kayitGorevlisiCikisMouseClicked

    private void doktorCikisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doktorCikisMouseClicked
        // TODO add your handling code here:
        doktorAnaSayfasi.setVisible(false);
        doktorSidePanel.setVisible(false);
        
        if(hastaBilgisiSayfasi != null){
            hastaBilgisiSayfasi.setVisible(false);
        }
        
        girisEkranPanel.setVisible(true);
        girisEkranSidePanel.setVisible(true);
    }//GEN-LAST:event_doktorCikisMouseClicked

    private void vezneCikisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vezneCikisMouseClicked
        // TODO add your handling code here:
        vezneAnaSayfasi.setVisible(false);
        vezneSidePanel.setVisible(false);
        
        if(hastaOdemeSayfasi != null){
            hastaOdemeSayfasi.setVisible(false);
        }
        
        girisEkranPanel.setVisible(true);
        girisEkranSidePanel.setVisible(true);
    }//GEN-LAST:event_vezneCikisMouseClicked

    private void vezneCikisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vezneCikisFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_vezneCikisFocusGained

    private void kullaniciTipComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciTipComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kullaniciTipComboBoxActionPerformed

    private void doktorIslemleriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doktorIslemleriMouseClicked
        // TODO add your handling code here:
        gorevliAnaSayfasi.setVisible(false);
        
        
        if(hastaRandevuSayfasi != null){
            hastaRandevuSayfasi.setVisible(false);
        }
        if(klinikEklemeSayfasi != null){
            klinikEklemeSayfasi.setVisible(false);
        }
        girisEkranPanel.setVisible(false);
        
        
        if(doktorEklemeSayfasi == null){
            doktorEklemeSayfasi = new DoktorEklemeSayfasi();
            mainPanel.add(doktorEklemeSayfasi);
        }
        
        doktorEklemeSayfasi.updateDoktorEkleKlinikComboBox();
        doktorEklemeSayfasi.setVisible(true);
    }//GEN-LAST:event_doktorIslemleriMouseClicked

    private void klinikIslemleriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_klinikIslemleriMouseClicked
        // TODO add your handling code here:
        gorevliAnaSayfasi.setVisible(false);
        
        if(hastaRandevuSayfasi != null){
            hastaRandevuSayfasi.setVisible(false);
        }
        if(doktorEklemeSayfasi != null){
            doktorEklemeSayfasi.setVisible(false);
        }
        girisEkranPanel.setVisible(false);
        
        if(klinikEklemeSayfasi == null){
            klinikEklemeSayfasi = new KlinikEklemeSayfasi();
            mainPanel.add(klinikEklemeSayfasi);
        }
        klinikEklemeSayfasi.setVisible(true);
    }//GEN-LAST:event_klinikIslemleriMouseClicked

    private void hastaRandevuIslemleriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hastaRandevuIslemleriMouseClicked
        // TODO add your handling code here:
        gorevliAnaSayfasi.setVisible(false);
        
        girisEkranPanel.setVisible(false);
        if(doktorEklemeSayfasi != null){
            doktorEklemeSayfasi.setVisible(false);
        }
        if(klinikEklemeSayfasi != null){
            klinikEklemeSayfasi.setVisible(false);
        }
        
        if(hastaRandevuSayfasi == null){
            hastaRandevuSayfasi = new HastaRandevuSayfasi();
            mainPanel.add(hastaRandevuSayfasi);
        }
        
        hastaRandevuSayfasi.updateRandevuKlinikComboBox();
        hastaRandevuSayfasi.setVisible(true);
    }//GEN-LAST:event_hastaRandevuIslemleriMouseClicked

    private void gorevliAnaSayfasiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gorevliAnaSayfasiLabelMouseClicked
        // TODO add your handling code here:
        girisEkranPanel.setVisible(false);
        if(doktorEklemeSayfasi != null){
            doktorEklemeSayfasi.setVisible(false);
        }
        if(klinikEklemeSayfasi != null){
            klinikEklemeSayfasi.setVisible(false);
        }
        if(hastaRandevuSayfasi != null){
            hastaRandevuSayfasi.setVisible(false);
        }
        
        gorevliAnaSayfasi.setVisible(true);
    }//GEN-LAST:event_gorevliAnaSayfasiLabelMouseClicked

    private void kayitGorevlisiAnaSayfasiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayitGorevlisiAnaSayfasiLabelMouseClicked
        // TODO add your handling code here:
        girisEkranPanel.setVisible(false);
        
        if(hastaKayitSayfasi != null){
            hastaKayitSayfasi.setVisible(false);
        }
        
        kayitGorevlisiAnaSayfasi.setVisible(true);
    }//GEN-LAST:event_kayitGorevlisiAnaSayfasiLabelMouseClicked

    private void hastaKayitIslemleriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hastaKayitIslemleriMouseClicked
        // TODO add your handling code here:
        girisEkranPanel.setVisible(false);
 
        kayitGorevlisiAnaSayfasi.setVisible(false);
        
        if(hastaKayitSayfasi == null){
            hastaKayitSayfasi = new HastaKayitSayfasi();
            mainPanel.add(hastaKayitSayfasi);
        }
        hastaKayitSayfasi.setVisible(true);
    }//GEN-LAST:event_hastaKayitIslemleriMouseClicked

    private void doktorAnaSayfasiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doktorAnaSayfasiLabelMouseClicked
        // TODO add your handling code here:
        girisEkranPanel.setVisible(false);
        
        if(hastaBilgisiSayfasi != null){
            hastaBilgisiSayfasi.setVisible(false);
        }
        
        doktorAnaSayfasi.setVisible(true);
    }//GEN-LAST:event_doktorAnaSayfasiLabelMouseClicked

    private void hastaBilsgiIslemleriLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hastaBilsgiIslemleriLabelMouseClicked
        // TODO add your handling code here:
        girisEkranPanel.setVisible(false);
        doktorAnaSayfasi.setVisible(false);
        
        if(hastaBilgisiSayfasi == null){
            hastaBilgisiSayfasi = new HastaBilgisiSayfasi(doktor);
            mainPanel.add(hastaBilgisiSayfasi);
        }
        hastaBilgisiSayfasi.updateTableWithArray();
        hastaBilgisiSayfasi.setVisible(true);
    }//GEN-LAST:event_hastaBilsgiIslemleriLabelMouseClicked

    private void vezneAnaSayfasiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vezneAnaSayfasiLabelMouseClicked
        // TODO add your handling code here:
        girisEkranPanel.setVisible(false);
        
        if(hastaOdemeSayfasi != null){
            hastaOdemeSayfasi.setVisible(false);
        }
        
        vezneAnaSayfasi.setVisible(true);
    }//GEN-LAST:event_vezneAnaSayfasiLabelMouseClicked

    private void hastaOdemeIslemleriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hastaOdemeIslemleriMouseClicked
        // TODO add your handling code here:
        girisEkranPanel.setVisible(false);
        vezneAnaSayfasi.setVisible(false);
        
        if(hastaOdemeSayfasi == null){
            hastaOdemeSayfasi = new HastaOdemeSayfasi();
            mainPanel.add(hastaOdemeSayfasi);
        }
        hastaOdemeSayfasi.setVisible(true);
    }//GEN-LAST:event_hastaOdemeIslemleriMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkrani().setVisible(true);
            }
        });
    }
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel doktorAnaSayfasiLabel;
    private javax.swing.JLabel doktorCikis;
    private javax.swing.JLabel doktorIslemleri;
    private javax.swing.JPanel doktorSidePanel;
    private javax.swing.JButton girisButton;
    private javax.swing.JPanel girisEkranPanel;
    private javax.swing.JPanel girisEkranSidePanel;
    private javax.swing.JLabel girisUyariMesaji;
    private javax.swing.JLabel gorevliAnaSayfasiLabel;
    private javax.swing.JLabel gorevliCikis;
    private javax.swing.JLabel gorevliIcon;
    private javax.swing.JLabel gorevliIcon1;
    private javax.swing.JPanel gorevliSidePanel;
    private javax.swing.JLabel hastaBilsgiIslemleriLabel;
    private javax.swing.JLabel hastaKayitIslemleri;
    private javax.swing.JLabel hastaOdemeIslemleri;
    private javax.swing.JLabel hastaRandevuIslemleri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel kayitGorevlisiAnaSayfasiLabel;
    private javax.swing.JLabel kayitGorevlisiCikis;
    private javax.swing.JLabel kayitGorevlisiIcon;
    private javax.swing.JPanel kayitGorevlisiSidePanel;
    private javax.swing.JLabel klinikIslemleri;
    private javax.swing.JComboBox<String> kullaniciTipComboBox;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JLabel vezneAnaSayfasiLabel;
    private javax.swing.JLabel vezneCikis;
    private javax.swing.JLabel vezneIcon;
    private javax.swing.JPanel vezneSidePanel;
    // End of variables declaration//GEN-END:variables

    
}
