/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sifapoliklinigi;

import java.awt.Component;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sayid, Majd
 */
public class hastaMuayenePaneli extends javax.swing.JPanel {

    /**
     * Creates new form hastaMuayenePanelii
     */
    
    private long hastaNo;
    private Doktor doktor;
    private Randevu randevu;
    PostgreConnector postgresql = new PostgreConnector();
    HastaBilgisiSayfasi hastaBilgisiSayfasi;
    
    public hastaMuayenePaneli(HastaBilgisiSayfasi hastaBilgisSayfasi, long hastaNo, Doktor doktor, Randevu randevu) {
        this.hastaBilgisiSayfasi = hastaBilgisSayfasi;
        this.hastaNo = hastaNo;
        this.doktor = doktor;
        this.randevu = randevu;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        aciklamaTextField = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        belgeComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ucretTextField = new javax.swing.JTextField();
        kaydetButon = new javax.swing.JButton();
        vazgecButon = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Muayen No", "Hasta Ad", "Hasta Soyad", "Açıklama"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Hasta Geçmişi");

        aciklamaTextField.setColumns(20);
        aciklamaTextField.setRows(5);
        jScrollPane2.setViewportView(aciklamaTextField);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Muayene Açıklaması");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Verilen Belge:");

        belgeComboBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        belgeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "Rapor", "Reçete" }));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Muayene Ücreti:");

        ucretTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ucretTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ucretTextFieldActionPerformed(evt);
            }
        });

        kaydetButon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        kaydetButon.setText("Kaydet");
        kaydetButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetButonActionPerformed(evt);
            }
        });

        vazgecButon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vazgecButon.setText("Vazgeç");
        vazgecButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vazgecButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kaydetButon, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ucretTextField)
                            .addComponent(vazgecButon, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(belgeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(belgeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ucretTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kaydetButon)
                            .addComponent(vazgecButon))
                        .addGap(84, 84, 84))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ucretTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ucretTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ucretTextFieldActionPerformed

    private void kaydetButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetButonActionPerformed
        // TODO add your handling code here:
        Connection conn = postgresql.getInstance();
        String aciklama = aciklamaTextField.getText();
        String ucret = ucretTextField.getText();
        
        if(!ucret.equals("")){
            try {
                String query = String.format(
                        "INSERT INTO MUAYENELER VALUES"
                        + "(DEFAULT, %d, %d, %d, \'%s\', \'%s\', %d);",
                        hastaNo, doktor.getKimlikNo(), Integer.parseInt(ucret),
                        aciklama, (String) belgeComboBox.getSelectedItem(), 0
                );
                
                conn.createStatement().executeUpdate(query);
                JOptionPane.showMessageDialog(this, "Başarı ile kaydedildi");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Hata");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Lütfen ücreti girin");
        }
        
        this.setVisible(false);
        hastaBilgisiSayfasi.updateTableWithArray();
        hastaBilgisiSayfasi.setVisible(true);
        
    }//GEN-LAST:event_kaydetButonActionPerformed

    private void vazgecButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vazgecButonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        hastaBilgisiSayfasi.updateTableWithArray();
        hastaBilgisiSayfasi.setVisible(true);
    }//GEN-LAST:event_vazgecButonActionPerformed

    
    public void updateTable(){
        Connection con = postgresql.connectorSender();
        
        int column_count;
        
        try{
            
            Statement stmt = con.createStatement();
            String Komut = String.format("SELECT MUAYENE_NO, HASTA_AD, HASTA_SOYAD, MUAYENE_ACIKLAMASI FROM KAYITLI_HASTALAR kh, MUAYENELER m"
                    + " WHERE kh.HASTA_NO = m.HASTA_NO and m.hasta_no = %d and m.DOKTOR_NO = %d ", hastaNo, this.doktor.getKimlikNo());
            ResultSet rs = stmt.executeQuery(Komut);
            ResultSetMetaData rsMetaData = rs.getMetaData();
            column_count = rsMetaData.getColumnCount();
            
            DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            
            while (rs.next()) {
                Vector v2 = new Vector();
                
                for(int a=1; a<=column_count; a++)
                {
                 
                    v2.add(rs.getString("MUAYENE_NO"));
                    v2.add(rs.getString("HASTA_AD"));             
                    v2.add(rs.getString("HASTA_SOYAD"));
                    v2.add(rs.getString("MUAYENE_ACIKLAMASI"));
            
                }
                df.addRow(v2);
            }
        } catch (SQLException e) {
            System.out.println(e);
            System.out.println("Exception");
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aciklamaTextField;
    private javax.swing.JComboBox<String> belgeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kaydetButon;
    private javax.swing.JTextField ucretTextField;
    private javax.swing.JButton vazgecButon;
    // End of variables declaration//GEN-END:variables
}
