/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sifapoliklinigi;

import javax.swing.JOptionPane;

/**
 *
 * @author sayid
 */
public class KlinikEklemeSayfasi extends javax.swing.JPanel {

    /**
     * Creates new form klinikEklemeSayfasi
     */
    
    private Klinik klinik;
    PostgreConnector postgresql = new PostgreConnector();
    
    
    public KlinikEklemeSayfasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        klinikAdTextField = new javax.swing.JTextField();
        klinikNoTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        klinikEkleButton = new javax.swing.JButton();

        klinikAdTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        klinikNoTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Kliniğin Adı");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Kliniğin Numarası");

        klinikEkleButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        klinikEkleButton.setText("Ekle");
        klinikEkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klinikEkleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(klinikAdTextField)
                        .addComponent(klinikNoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                    .addComponent(klinikEkleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(klinikAdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(klinikNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(klinikEkleButton)
                .addContainerGap(160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void klinikEkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klinikEkleButtonActionPerformed
        // TODO add your handling code here:
        
        if(checkComponent()){
            klinik = new Klinik(Integer.parseInt(klinikNoTextField.getText()), klinikAdTextField.getText());
            if(klinik.veriTabaninaIsle()){
                JOptionPane.showMessageDialog(this, "Yeni klinik başarıyla eklenmiştir");
            }else{
                JOptionPane.showMessageDialog(this, "Hata Oluştu, Lütfen Bilgileri Kontrol Ediniz");
            }
         
        }
    }//GEN-LAST:event_klinikEkleButtonActionPerformed

    public boolean checkComponent(){
        return !klinikAdTextField.getText().equals("") && !klinikNoTextField.getText().equals("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField klinikAdTextField;
    private javax.swing.JButton klinikEkleButton;
    private javax.swing.JTextField klinikNoTextField;
    // End of variables declaration//GEN-END:variables
}
