/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sifapoliklinigi;

import javax.swing.JOptionPane;

/**
 *
 * @author sayid
 */
public class VezneAnaSayfasi extends javax.swing.JPanel {

    /**
     * Creates new form vezneAnaSayfasi
     */
    
    private final Gorevli gorevli;
    PostgreConnector postgresql = new PostgreConnector();
    
    public VezneAnaSayfasi(Gorevli gorevli) {
        this.gorevli = gorevli;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vezneAdSoyadProfil = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        vezneKullaniciAdiLabel = new javax.swing.JLabel();
        vezneKullaniciAdTextField = new javax.swing.JTextField();
        vezneSifreTextField = new javax.swing.JTextField();
        vezneGuncelleButon = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        vezneDuyuruTextField = new javax.swing.JTextArea();
        vezneDuyurLabel = new javax.swing.JLabel();
        vezneTarihLabel = new javax.swing.JLabel();
        vezneSifreLabel = new javax.swing.JLabel();

        vezneAdSoyadProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sifapoliklinigi/icons8-male-user-32.png"))); // NOI18N
        vezneAdSoyadProfil.setText("Ad Soyad");

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setText("Bilgileri Güncelleme:");

        vezneKullaniciAdiLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vezneKullaniciAdiLabel.setText("Yeni Kullanıcı Adınız");

        vezneKullaniciAdTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        vezneSifreTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        vezneGuncelleButon.setText("Güncelle");
        vezneGuncelleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vezneGuncelleButonActionPerformed(evt);
            }
        });

        vezneDuyuruTextField.setEditable(false);
        vezneDuyuruTextField.setColumns(20);
        vezneDuyuruTextField.setRows(5);
        vezneDuyuruTextField.setText("Dikkat Covid19");
        jScrollPane4.setViewportView(vezneDuyuruTextField);

        vezneDuyurLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vezneDuyurLabel.setText("Duyurular:");

        vezneTarihLabel.setText("Tarih");

        vezneSifreLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vezneSifreLabel.setText("Yeni şifreniz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vezneAdSoyadProfil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vezneTarihLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vezneKullaniciAdiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vezneSifreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vezneGuncelleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vezneKullaniciAdTextField)
                            .addComponent(vezneSifreTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vezneDuyurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vezneAdSoyadProfil)
                            .addComponent(vezneTarihLabel))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(vezneDuyurLabel))
                        .addGap(43, 43, 43)
                        .addComponent(vezneKullaniciAdiLabel)
                        .addGap(18, 18, 18)
                        .addComponent(vezneKullaniciAdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vezneSifreLabel))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(vezneSifreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(vezneGuncelleButon)
                .addContainerGap(203, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vezneGuncelleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vezneGuncelleButonActionPerformed
        // TODO add your handling code here:
        String yeniKullaniciAd = vezneKullaniciAdTextField.getText();
        String yeniKullaniciSifre = vezneSifreTextField.getText();
        if(checkComponent()){
            gorevli.setKullaniciAd(yeniKullaniciAd);
            gorevli.setSifre(yeniKullaniciSifre);
            JOptionPane.showMessageDialog(this, "Kullanıcı Adınız ve Şifreniz Güncellenmiştir");
        }else if(yeniKullaniciAd.equals("")){
            gorevli.setSifre(yeniKullaniciSifre);
            JOptionPane.showMessageDialog(this, "Şifreniz Güncellenmiştir");
        }else if(yeniKullaniciSifre.equals("")){
            gorevli.setKullaniciAd(yeniKullaniciAd);
            JOptionPane.showMessageDialog(this, "Kullanıcı Adınız Güncellenmiştir");
        }else{
            JOptionPane.showMessageDialog(this, "Boş Alanları Doldurunuz");
        }
    }//GEN-LAST:event_vezneGuncelleButonActionPerformed

    public void setVezneAdSoyadProfil(String vezneAdSoyadProfil) {
        this.vezneAdSoyadProfil.setText(vezneAdSoyadProfil);
    }

    public void setVezneTarihLabel(String vezneTarihLabel) {
        this.vezneTarihLabel.setText(vezneTarihLabel);
    }
    
    public boolean checkComponent(){
        return !vezneKullaniciAdTextField.getText().equals("") && !vezneSifreTextField.getText().equals("");
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel33;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel vezneAdSoyadProfil;
    private javax.swing.JLabel vezneDuyurLabel;
    private javax.swing.JTextArea vezneDuyuruTextField;
    private javax.swing.JButton vezneGuncelleButon;
    private javax.swing.JTextField vezneKullaniciAdTextField;
    private javax.swing.JLabel vezneKullaniciAdiLabel;
    private javax.swing.JLabel vezneSifreLabel;
    private javax.swing.JTextField vezneSifreTextField;
    private javax.swing.JLabel vezneTarihLabel;
    // End of variables declaration//GEN-END:variables
}
